server:
  port: 8080
spring:
  application:
    name: online-store
  datasource:
    url: jdbc:h2:mem:purchase;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  properties:
    hibernate:
      validator:
        apply_to_ddl: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
        globally_quoted_identifiers: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: rabbitAdmin

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type: INFO
